const Jokes = [
  "Why don’t scientists trust atoms? Because they make up everything! 😂",
  "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats! 🍫",
  "Why did the scarecrow win an award? Because he was outstanding in his field! 🌾😆",
  "Parallel lines have so much in common. It’s a shame they’ll never meet. 😢",
  "Why don’t skeletons fight each other? They don’t have the guts. 💀",
  "I would tell you a joke about an elevator, but it’s an uplifting experience! 🚀",
  "Why did the math book look sad? Because it had too many problems. 📚",
  "I told my wife she was drawing her eyebrows too high. She looked surprised. 😲",
  "Why don’t some couples go to the gym? Because some relationships don’t work out. 💪",
  "I’m reading a book on anti-gravity. It’s impossible to put down! 📖",
  "Why did the bicycle fall over? Because it was two-tired! 🚲",
  "I told my dog a joke and he laughed his tail off! 🐶",
  "Why did the coffee file a police report? It got mugged! ☕",
  "I used to play piano by ear, but now I use my hands. 🎹",
  "Why did the tomato turn red? Because it saw the salad dressing! 🍅",
  "I would tell you a joke about a roof, but it’s over your head. 🏠",
  "Why don’t oysters donate to charity? Because they are shellfish. 🦪",
  "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did. 😂",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one! ⛳",
  "Why did the chicken join a band? Because it had the drumsticks! 🥁",
  "Why don’t programmers like nature? It has too many bugs. 🐛",
  "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field. 🧠",
  "Why did the computer go to the doctor? Because it had a virus! 🖥️",
  "Why did the banana go to the doctor? Because it wasn’t peeling well. 🍌",
  "Why did the math teacher break up with the biology teacher? There was no chemistry. 🧪",
  "Why did the music teacher go to jail? Because she got caught with too many notes. 🎵",
  "Why did the picture go to jail? Because it was framed. 🖼️",
  "Why did the bicycle stand up by itself? Because it was two-tired. 🚲",
  "Why did the scarecrow win an award? Because he was outstanding in his field. 🌾",
  "Why did the tomato turn red? Because it saw the salad dressing. 🍅",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one. ⛳",
  "Why did the computer go to the doctor? Because it had a virus. 🖥️",
  "Why did the math book look sad? Because it had too many problems. 📚",
  "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field. 🧠",
  "Why did the chicken join a band? Because it had the drumsticks. 🥁",
  "Why did the coffee file a police report? It got mugged. ☕",
  "Why did the banana go to the doctor? Because it wasn’t peeling well. 🍌",
  "Why did the music teacher go to jail? Because she got caught with too many notes. 🎵",
  "Why did the picture go to jail? Because it was framed. 🖼️",
  "Why did the bicycle stand up by itself? Because it was two-tired. 🚲",
];

const MetaPrompt = [
    "Generate a funny joke about technology.",
    "Write a humorous short story involving a robot.",
    "Create a witty article about the daily life of a programmer.",
    "Come up with a hilarious scenario involving artificial intelligence.",
    "Generate a pun-filled joke about computers.",
    "Write a funny dialogue between two chatbots.",
    "Create a humorous poem about coding.",
    "Generate a light-hearted story about a day in the life of a software engineer.",
    "Write a funny article about the quirks of working from home.",
    "Come up with a joke about debugging code.",
    "Write a longer joke that involves a programmer and a bug.",
    "Create a humorous story about a robot trying to understand human emotions.",
    "Generate a witty article about the evolution of technology over the decades.",
    "Write a funny dialogue between a programmer and their computer.",
    "Come up with a hilarious scenario where artificial intelligence tries to take over the world but fails.",
    "Generate a pun-filled story about a day in the life of a tech support agent.",
    "Write a humorous poem about the struggles of learning to code.",
    "Create a light-hearted story about a programmer's adventures in a virtual reality world.",
    "Generate a funny article about the common mistakes programmers make.",
    "Write a longer joke involving a computer, a programmer, and a surprising twist."
];

module.exports = {
  Jokes,
  MetaPrompt,
};
